### ISSUE TITLE
Abort connection. Upload not work.

### ISSUE THREAD

**Issue by m9w** [ezhov-evgeny/webdav-client-python-3#24]
```
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from webdav3.client import Client
>>> options = {
...  'webdav_hostname': "https://webdav.yandex.ru",
...  'webdav_login':    "my_login",
...  'webdav_password': "my_pass"
... }
>>> client = Client(options)
>>> client.free()
10737418240
>>> client.list()
['33/', '55.txt']
>>> client.upload_sync(remote_path="33/123.txt", local_path="C:\\Users\\USER\\Desktop\\123.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 497, in upload_sync
    self.upload(local_path=local_path, remote_path=remote_path)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 433, in upload
    self.upload_file(local_path=local_path, remote_path=remote_path)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 68, in _wrapper
    res = fn(self, *args, **kw)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 484, in upload_file
    raise RemoteParentNotFound(urn.path())
webdav3.exceptions.RemoteParentNotFound: Remote parent for: /33/123.txt not found
>>> client.upload_sync(remote_path="33\\123.txt", local_path="C:\\Users\\USER\\Desktop\\123.txt")
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 68, in _wrapper
    res = fn(self, *args, **kw)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 280, in check
    response = self.execute_request(action='check', path=urn.quote())
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 162, in execute_request
    response = self.session.request(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 239, in resolve_redirects
    resp = self.send(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 497, in upload_sync
    self.upload(local_path=local_path, remote_path=remote_path)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 433, in upload
    self.upload_file(local_path=local_path, remote_path=remote_path)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 68, in _wrapper
    res = fn(self, *args, **kw)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 483, in upload_file
    if not self.check(urn.parent()):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 70, in _wrapper
    raise NoConnection(self.webdav.hostname)
webdav3.exceptions.NoConnection: Not connection with https://webdav.yandex.ru
>>> client.upload_sync(remote_path="123.txt", local_path="C:\\Users\\USER\\Desktop\\123.txt")
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 68, in _wrapper
    res = fn(self, *args, **kw)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 280, in check
    response = self.execute_request(action='check', path=urn.quote())
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 162, in execute_request
    response = self.session.request(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 239, in resolve_redirects
    resp = self.send(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 497, in upload_sync
    self.upload(local_path=local_path, remote_path=remote_path)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 433, in upload
    self.upload_file(local_path=local_path, remote_path=remote_path)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 68, in _wrapper
    res = fn(self, *args, **kw)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 483, in upload_file
    if not self.check(urn.parent()):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\webdav3\client.py", line 70, in _wrapper
    raise NoConnection(self.webdav.hostname)
webdav3.exceptions.NoConnection: Not connection with https://webdav.yandex.ru
```

**Comment by ezhov-evgeny** [comment]
Please try on your environment fix from branch https://github.com/ezhov-evgeny/webdav-client-python-3/tree/bugfix/1-broken-upload-on-yandex-server
If it is fixed I'll publish it

**Comment by m9w** [comment]
Thanks, i got full message 
`
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yandex.ru', port=443): Max retries exceeded with url: /support/disk/webdav.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0343CC70>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера'))`
it's happend because urllib3 not use 8.8.8.8 DNS. I connected VPN and got sucsess result.
Diferent ip's:
`Обмен пакетами с yandex.ru [5.255.255.88] с 32 байтами данных:
Ответ от 5.255.255.88: число байт=32 время=46мс TTL=55
...`
`C:\Users\USER>ping webdav.yandex.ru
Обмен пакетами с webdav.yandex.ru [213.180.204.148] с 32 байтами данных:
Ответ от 213.180.204.148: число байт=32 время=45мс TTL=56
...`
But I still can’t understand why need a query to a domain one level higher. I use AirLiveDrive and Yandex webdav is working correctly.

**Comment by m9w** [comment]
I think you can simulate my situation if you block 5.255.255.88 in the firewall. In this case, even the built-in Windows network webdav drive works, but the library does not. Thanks.

**Comment by ezhov-evgeny** [comment]
I've blocked 5.255.255.88 and with Yandex, all tests are passed successfully include for `upload_sync`.
Can you debug when it tries to get  /support/disk/webdav.xml?

**Comment by m9w** [comment]
no VPN: (Windows webdav work correctly.)
`>>> c.mkdir("rtf")`
> Traceback (most recent call last):
>   File "C:\python3.8\lib\site-packages\urllib3\connection.py", line 156, in _new_conn
>     conn = connection.create_connection(
>   File "C:\python3.8\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
>     raise err
>   File "C:\python3.8\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\python3.8\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
>     httplib_response = self._make_request(
>   File "C:\python3.8\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
>     self._validate_conn(conn)
>   File "C:\python3.8\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
>     conn.connect()
>   File "C:\python3.8\lib\site-packages\urllib3\connection.py", line 334, in connect
>     conn = self._new_conn()
>   File "C:\python3.8\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x04B35658>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\python3.8\lib\site-packages\requests\adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "C:\python3.8\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
>     retries = retries.increment(
>   File "C:\python3.8\lib\site-packages\urllib3\util\retry.py", line 436, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='yandex.ru', port=443): Max retries exceeded with url: /support/disk/webdav.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04B35658>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\python3.8\lib\site-packages\webdav3\client.py", line 68, in _wrapper
>     res = fn(self, *args, **kw)
>   File "C:\python3.8\lib\site-packages\webdav3\client.py", line 280, in check
>     response = self.execute_request(action='check', path=urn.quote())
>   File "C:\python3.8\lib\site-packages\webdav3\client.py", line 162, in execute_request
>     response = self.session.request(
>   File "C:\python3.8\lib\site-packages\requests\sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\python3.8\lib\site-packages\requests\sessions.py", line 668, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "C:\python3.8\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
>     history = [resp for resp in gen] if allow_redirects else []
>   File "C:\python3.8\lib\site-packages\requests\sessions.py", line 239, in resolve_redirects
>     resp = self.send(
>   File "C:\python3.8\lib\site-packages\requests\sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\python3.8\lib\site-packages\requests\adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yandex.ru', port=443): Max retries exceeded with url: /support/disk/webdav.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04B35658>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<pyshell#1>", line 1, in <module>
>     c.mkdir("rtf")
>   File "C:\python3.8\lib\site-packages\webdav3\client.py", line 68, in _wrapper
>     res = fn(self, *args, **kw)
>   File "C:\python3.8\lib\site-packages\webdav3\client.py", line 300, in mkdir
>     if not self.check(directory_urn.parent()):
>   File "C:\python3.8\lib\site-packages\webdav3\client.py", line 70, in _wrapper
>     raise NoConnection(self.webdav.hostname)
> webdav3.exceptions.NoConnection: Not connection with https://webdav.yandex.ru

with VPN
`>>> c.mkdir("rtf")`
True

**Comment by m9w** [comment]
![55Снимок](https://user-images.githubusercontent.com/52008918/69899555-b0b2e380-1370-11ea-959c-0330cf7f57b9.JPG)
I seen dead package.

**Comment by m9w** [comment]
I fix all my troubles and sharing my changes.
[client.zip](https://github.com/ezhov-evgeny/webdav-client-python-3/files/3907438/client.zip)
