### ISSUE TITLE
RemoteResourceNotFound for info, download, rename...

### ISSUE THREAD

**Issue by bsteverink** [ezhov-evgeny/webdav-client-python-3#27]
while using the webdav-client for python 3 I experience an issue very similar to [CloudPolis#18](https://github.com/CloudPolis/webdav-client-python/issues/18) and [CloudPolis#22](https://github.com/CloudPolis/webdav-client-python/issues/22).

I can list contents of a directory and check if a file exists but cannot get info or perform any resource operations (rename, move, etc). Uploading goes without any issues.

I have tried setting the root to /remote.php/webdav as suggested in the CloudPolis solutions but that seems to limit the number of folders I can see. It does reveal the info.

The webdav server I am trying to connect to called Stack and is a service of TransIP [stack](https://www.transip.nl/stack/)

The version of the client is webdavclient3==0.12.

**Comment by ezhov-evgeny** [comment]
@bsteverink Can you provide DEBUG logs?

**Comment by ezhov-evgeny** [comment]
@bsteverink is it actual?

**Comment by jackedproxy** [comment]
Having a very similar issue, although info just returns "None" for all parameters with the exception of the date.
Here's a part of the code:

```
def Download():
		client = wc.Client(SyncBits.CryptSyncVars())
		try:
                    JoplinRemote = ("/PortableArray/Latest/PortableArray/Windows/Joplin/")
		    JoplinRemoteReady = client.check(JoplinRemote)
                    JoplinLocal = ("{}\\Windows\\Joplin\\" .format(path))
	            JoplinLocalReady = os.path.exists(JoplinLocal)
		    info = client.info(JoplinRemote)
		    check = client.check(JoplinRemote)
		    print(info)
		    print(check)
	            print(path)
                    if (JoplinRemoteReady, JoplinLocalReady):
				print("Connected! Caught PortableArray!")
				ThePull = client.download_sync(remote_path=JoplinRemote, local_path=JoplinLocal)
```

Here's the error:

```
Received Download!
{'created': None, 'name': None, 'size': None, 'modified': 'Wed, 08 Jan 2020 19:47:13 GMT'}
True
C:\Users\multiplexer\Documents\PortableArray
Connected! Caught PortableArray!
Traceback (most recent call last):
  File "ArrayDeploymentSyncEX.py", line 211, in <module>
    menu()
  File "ArrayDeploymentSyncEX.py", line 71, in menu
    SyncBits.Download()
  File "ArrayDeploymentSyncEX.py", line 137, in Download
    ThePull = client.download_sync(remote_path=JoplinRemote, local_path=JoplinLocal)
  File "C:\Users\multiplexer\AppData\Local\Programs\Python\Python37\lib\site-packages\webdav3\client.py", line 399, in download_sync
    self.download(local_path=local_path, remote_path=remote_path)
  File "C:\Users\multiplexer\AppData\Local\Programs\Python\Python37\lib\site-packages\webdav3\client.py", line 342, in download
    self.download_directory(local_path=local_path, remote_path=remote_path, progress=progress)
  File "C:\Users\multiplexer\AppData\Local\Programs\Python\Python37\lib\site-packages\webdav3\client.py", line 366, in download_directory
    self.download(local_path=_local_path, remote_path=_remote_path, progress=progress)
  File "C:\Users\multiplexer\AppData\Local\Programs\Python\Python37\lib\site-packages\webdav3\client.py", line 341, in download
    if self.is_dir(urn.path()):
  File "C:\Users\multiplexer\AppData\Local\Programs\Python\Python37\lib\site-packages\webdav3\client.py", line 69, in _wrapper
    res = fn(self, *args, **kw)
  File "C:\Users\multiplexer\AppData\Local\Programs\Python\Python37\lib\site-packages\webdav3\client.py", line 611, in is_dir
    self._check_remote_resource(remote_path, urn)
  File "C:\Users\multiplexer\AppData\Local\Programs\Python\Python37\lib\site-packages\webdav3\client.py", line 599, in _check_remote_resource
    raise RemoteResourceNotFound(remote_path)
webdav3.exceptions.RemoteResourceNotFound: Remote resource: /PortableArray/Latest/PortableArray/Windows/Joplin/Joplin/ not found
```

Notice how the remote_path has the last directory in the given path duplicated:
_webdav3.exceptions.RemoteResourceNotFound: Remote resource: /PortableArray/Latest/PortableArray/Windows/Joplin/Joplin/ not found_

I've been scratching my head trying to figure out why that happens. 
The `client.check(JoplinRemote) ` returns True though, so I'm unsure what I'm missing:
_JoplinRemote = ("/PortableArray/Latest/PortableArray/Windows/Joplin/")_

**Comment by ezhov-evgeny** [comment]
@jackedproxy @bsteverink Can you provide options (of course without credentials) which you use for creating client? I can not reproduce this problem.

**Comment by jackedproxy** [comment]
```
options = {
			a1: a2,  # URL
			b1: b2,  # User
			c1: c2,  # Password
			d1: True,  # Verbosity
			'webdav_root': "/"
		}
		return options
```

I've since resolved the issue, I suspect I had some weird formatting happening as I've been encoding my  options.  It's working fine now, with the following:

```
downparams = {'ZippedRemoteJoplinResources': ("PortableArray/Latest/JoplinProfile.7z"),
			'ZippedLocalJoplinResources': ("{}\\Windows\\Joplin\\JoplinProfile.7z" .format(path)),
			'LocalJoplinResources': ("{}\\Windows\\Joplin" .format(path))
		}
  #(...)
client.download_sync(remote_path=(downparams['ZippedRemoteJoplinResources']), local_path=(downparams['ZippedLocalJoplinResources']))
					print("Joplin Resources pulled...")
```

**Comment by ezhov-evgeny** [comment]
@bsteverink @jackedproxy try new version 3.14.2 it should be resolved there
