### ISSUE TITLE
Verify credentials

### ISSUE THREAD

**Issue by danijoo** [ezhov-evgeny/webdav-client-python-3#82]
Hi,

When I tried to download a file using the code below, I got a `RemoteResourceNotFound` error:

```python
from webdav3.client import Client
    webdav = Client({
        "webdav_hostname": "XXXX",
        "webdav_login":  "XXXX",
        "webdav_password":  "XXXX"
        })
webdav.download_sync(remote_path="some filename", local_path="some path")
```

```
Traceback (most recent call last):
[..]
  File "/home/bauer/conda/lib/python3.7/site-packages/webdav3/client.py", line 409, in download_sync
    self.download(local_path=local_path, remote_path=remote_path)
  File "/home/bauer/conda/lib/python3.7/site-packages/webdav3/client.py", line 349, in download
    if self.is_dir(urn.path()):
  File "/home/bauer/conda/lib/python3.7/site-packages/webdav3/client.py", line 66, in _wrapper
    res = fn(self, *args, **kw)
  File "/home/bauer/conda/lib/python3.7/site-packages/webdav3/client.py", line 622, in is_dir
    self._check_remote_resource(remote_path, urn)
  File "/home/bauer/conda/lib/python3.7/site-packages/webdav3/client.py", line 610, in _check_remote_resource
    raise RemoteResourceNotFound(remote_path)
webdav3.exceptions.RemoteResourceNotFound: Remote resource: /HUUD55DU.zip not found
```

After some debugging I realized that the source of this error was not a missing file, but wrong credentials. More specifically the password was not correct. I think the error is misleading here, since it does not point to missing credentials. Additionally, I wonder if there is a way to verify login credentials before making any other request? I didn't find one.

**Comment by edekeijzer** [comment]
I'm running into the same with checking a file path. Wrong credentials just result in the check returning a False. My workaround is to do a _webdav.free()_ first, which will actually return an HTTP status 401 exception when failed:
```
from webdav3.client import Client
from webdav3.exceptions import WebDavException
davoptions = {
    'webdav_hostname': "https://webdav.server.com",
    'webdav_login':    "username",
    'webdav_password': "password",
    'webdav_timeout': 30,
}

webdav = Client(davoptions)

try:
    dav_free = webdav.free()
except WebDavException as exception:
    print("HTTP error encountered: ", exception.code)
else:
    print("Free space: ", dav_free, " bytes")
```
